
CREATE DATABASE CINEMA_LETTER
GO
USE CINEMA_LETTER
GO
--SIGNIN--
CREATE TABLE SIGNIN
(
ID INT IDENTITY PRIMARY KEY,
TK VARCHAR (50)  NOT NULL,
MK VARCHAR (50) NOT NULL,
HOTEN NVARCHAR(50),
GIOITINH NVARCHAR(5),
NGAYSINH VARCHAR(50),
SDT VARCHAR (10),
GMAIL VARCHAR(30),
LOAITK INT DEFAULT 2 -- 1:admin || 2:customer
)
INSERT INTO  SIGNIN(TK,MK,LOAITK) VALUES('admin','lhWkMLxyLFg=',1)
--MOVIE
CREATE TABLE MOVIE
(
IDPHIM INT  PRIMARY KEY,
TENPHIM NVARCHAR(100)  DEFAULT N'Đang cập nhật',
THELOAI NVARCHAR(100) DEFAULT N'Đang cập nhật',
THOILUONG NVARCHAR(50) DEFAULT N'Đang cập nhật',
POSTER  NTEXT, 
DEMO  NTEXT DEFAULT N'Đang cập nhật',
NGAYKHOICHIEU NVARCHAR(50)DEFAULT N'Đang cập nhật',
QUOCGIA nvarchar(50) DEFAULT N'Đang cập nhật',
DAODIEN nvarchar(100) DEFAULT N'Đang cập nhật',
DIENVIEN NVARCHAR(200)DEFAULT N'Đang cập nhật',
MOTA NTEXT DEFAULT N'Đang cập nhật'
)
GO
--THEATER
CREATE TABLE THEATER
(
IDPHONG VARCHAR(10) PRIMARY KEY,
RAP   VARCHAR(10),
TINHTRANG INT  DEFAULT 0, -- 0:không hoạt động || 1:đang hoạt động
)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('2D1','2D',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('2D2','2D',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('2D3','2D',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('4dX1','4dX',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('4dX2','4dX',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('4dX3','4dX',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('CP1','COUPLE',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('CP2','COUPLE',1)
INSERT INTO  THEATER(IDPHONG,RAP,TINHTRANG) VALUES('CP3','COUPLE',1)


--TICKET
CREATE TABLE TICKET
(
	ID int IDENTITY PRIMARY KEY,
	IDNGUOIDAT INT,
	GHEDAT NVARCHAR(100),
	TONGTIEN NTEXT,
	PHIM NVARCHAR(100),
	PHONG VARCHAR(10),
	NGAYCHIEU VARCHAR(30),
	NGUOIDAT NVARCHAR(50),
	POSTER NTEXT
)

CREATE TABLE STATUSS
( 
  VITRI NVARCHAR(50),
  TINHTRANG INT,-- 0:trống || 1:có người đặt
  IDSUATCHIEU INT
)
CREATE TABLE SHOW
(
 IDPHIM INT,
 IDPHONG VARCHAR(10),
 NGAYCHIEU VARCHAR(30),
 IDSUATCHIEU INT PRIMARY KEY,
 Rap VARCHAR(10)
)
CREATE TABLE SUPPORT
(  
 ID INT  IDENTITY PRIMARY KEY ,
 HOTEN NVARCHAR(100),
 GMAIL NVARCHAR(100),
 SDT NVARCHAR(100),
 NOIDUNG NTEXT
)
CREATE TABLE NEWS
(  
 ID INT  IDENTITY PRIMARY KEY ,
TIEUDE NTEXT,
NOIDUNG NTEXT,
POSTER NTEXT
)

ALTER TABLE SHOW ADD CONSTRAINT FK_IDPHIM FOREIGN KEY(IDPHIM) REFERENCES MOVIE(IDPHIM)
ALTER TABLE SHOW ADD CONSTRAINT FK_IDPHONG FOREIGN KEY(IDPHONG) REFERENCES THEATER(IDPHONG)
ALTER TABLE STATUSS ADD CONSTRAINT FK_IDSUATCHIEU2 FOREIGN KEY(IDSUATCHIEU) REFERENCES SHOW(IDSUATCHIEU)
ALTER TABLE TICKET ADD CONSTRAINT FK_IDNGUOIDAT FOREIGN KEY(IDNGUOIDAT) REFERENCES SIGNIN(ID)
ALTER TABLE TICKET ADD CONSTRAINT FK_IDPHONG2 FOREIGN KEY(PHONG) REFERENCES THEATER(IDPHONG)

